---
- name: Install Java
  ansible.builtin.yum:
    name: java-1.8.0-openjdk-devel
    state: present 
    
- name: Create teamcity agent install directory
  ansible.builtin.file:
    path: "{{ teamcity_agent_install_dir }}"
    state: directory
    mode: "0755"

- name: Download Agent zip
  ansible.builtin.get_url:
    url: "{{ teamcity_buildagent_zip_url }}"
    dest: "{{ teamcity_downloaded_buildagent_zip }}"
    mode: 0775

- name: Install Teamcity Agent
  ansible.builtin.include_tasks:
    file: install_agent.yml
